[Definition]
actionstart =
actionstop =
actioncheck =
actionban = curl -s -X POST "https://api.telegram.org/bot@TELEGRAM_BOT_TOKEN@/sendMessage" \
            -d "chat_id=@TELEGRAM_CHAT_ID@" \
            -d "parse_mode=Markdown" \
            -d "text=*[FAIL2BAN BAN]*%0ANode: `$(hostname)`%0AJail: `<name>`%0ABanned IP: `<ip>`%0AFailures: `<failures>`"
actionunban =
